version: "3.9"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./local/index:/var/www/html
      - ./local/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./local/index:/var/www/html